### ISSUE TITLE
there is no Arabic version from this page 

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#10]
https://syrianarchive.org/en/collections/russian-airstrikes/errors_and_corrections.html

there is no Arabic version from this page

**Comment by tareefdev** [comment]
@Haneenk  please add one and push to the repo

**Comment by Haneenk** [comment]
https://github.com/syrianarchive/syrianarchive-investigations/blob/master/collections/russian-airstrikes/errors_and_corrections_ar.md

**Comment by tareefdev** [comment]
Fixed, thanks.
