### ISSUE TITLE
Strings in Header and Footer

### ISSUE THREAD

**Issue by tareefdev** [syrianarchive/syrianarchive-http#10]
We have some strings in header and footer which need to be translated to Arabic:

![screenshot from 2017-11-28 17-01-50](https://user-images.githubusercontent.com/17391433/33323660-4255ed72-d45e-11e7-873d-629d02ac0bb5.png)
![screenshot from 2017-11-28 17-02-00](https://user-images.githubusercontent.com/17391433/33323664-475f12da-d45e-11e7-9311-58ad14b2673e.png)

in which file I can find these strings?

**Comment by nikonikoniko** [comment]
I can add them to `translations.json`

feel free to add them yourself as you see them, too!
the key is the english (what you see untranslated) and the value is the arabic.

The main "Syrian Archive" that you see there is actually from the `Pages/index_ar.md` file

**Comment by nikonikoniko** [comment]
Could you write the translations in this ticket?

I also need "press" and "support"  and "latest investigations"

**Comment by tareefdev** [comment]
I just updated the translations.json file, It contains all the missing strings now.

**Comment by nikonikoniko** [comment]
thanks @tareefdev !
