### ISSUE TITLE
empty page 

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#12]
https://syrianarchive.org/ar/collections/all/

this page is empty in both Arabic and English versions

**Comment by tareefdev** [comment]
@nikonikoniko we don't need this, right?

**Comment by nikonikoniko** [comment]
hey!  we should just link that directly to /all/database

you can do that by changing the link in `mnemonic-archive-http` routes, to render the collection at the `all` root

**Comment by tareefdev** [comment]
Thank Niko, done.
