### ISSUE TITLE
mobile version - latest release 

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#15]
![photo_2018-12-04_19-04-44](https://user-images.githubusercontent.com/36305374/49455399-2d5fc000-f7f8-11e8-90a9-d0f5721b361e.jpg)

the "latest release" box  appears in the middle of the home page, not in the top (In both Arabic and English versions)

**Comment by tareefdev** [comment]
@nikonikoniko I'm thinking in make latest-release block a macro, to render it twice,  the first would be under the first section and the second in its current position, and then use CSS to display just one depends on screen size?

**Comment by nikonikoniko** [comment]
sure, sounds good to me
