### ISSUE TITLE
mobile version - video 

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#16]
![photo_2018-12-04_19-04-50](https://user-images.githubusercontent.com/36305374/49455727-b1b24300-f7f8-11e8-91e8-d3205f20472e.jpg)

https://syrianarchive.org/en/collections/russian-airstrikes/

there is a problem with playing video in the mobile version (in both EN and  AR versions)

**Comment by tareefdev** [comment]
@nikonikoniko Firefox on Android couldn't play the video.
[Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) says 'MP4s encoded with a high profile will not run on lower end hardware, such as low end phones.' Although my test was on Samsun S8 but I got the same error (!), at the same time the Chemical database's video is playing nice on the same device.

The use of `mediainfo` command shows the Russian video has `High@L4` profile, while Chemical one has `main@l3.2`.

**Comment by tareefdev** [comment]
@nikonikoniko Re-encode the file using the main profile fixes the problem, how could I upload the new file to the media server?

**Comment by tareefdev** [comment]
@nikonikoniko Could you please confirm if the new video was uploaded to the server? Because the video still doesn't work on Firefox, and I'm going to investigate it again.

**Comment by tareefdev** [comment]
Fixed.
