### ISSUE TITLE
mobile version -  tables fields' titles

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#17]
![photo_2018-12-04_19-04-53](https://user-images.githubusercontent.com/36305374/49455970-29806d80-f7f9-11e8-9546-dd53ca00ec22.jpg)

https://syrianarchive.org/en/collections/russian-airstrikes/pattern_of_attack.html

the tables fields' titles don't appear correctly in the mobile version (in both AR and EN  versions)

**Comment by tareefdev** [comment]
Thanks. Fixed.
