### ISSUE TITLE
mobile version - redundant spaces in the footer

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#18]
![photo_2018-12-04_19-04-41](https://user-images.githubusercontent.com/36305374/49456355-04402f00-f7fa-11e8-9f2b-2bdc2bddcf24.jpg)

the footer occupies a lot of space in the mobile version

**Comment by tareefdev** [comment]
@nikonikoniko maybe this is a little bit better 
![footer](https://user-images.githubusercontent.com/17391433/49528612-4e421700-f8c5-11e8-834c-c94da53e1c53.png)

**Comment by tareefdev** [comment]
Fixed.
