### ISSUE TITLE
Make Press and Support headers

### ISSUE THREAD

**Issue by j-deutch** [syrianarchive/syrianarchive-http#19]
Database; Map; Press; Contact; Support.

I think it's actually important to have those up top rather than buried inside the about page.

If you are worried about it looking to busy, remove the contact from above because it's also below

**Comment by nikonikoniko** [comment]
Investigations?  what should the full list be now?  i removed support a while ago

**Comment by j-deutch** [comment]
I would put support back as main header if it's removed. But it wasn't when I looked last.  If people want to donate or volunteer I want to make it easy for them to do so.

jeff deutch
tel: +49(0)1743203920
xmpp: jeff_d@jabber.ccc.de
pgp: CCBA 6A08 1CF6 7BA1 809F 72FD 904B F204 78E

**Comment by nikonikoniko** [comment]
So can you write the full list out again?  where would about be?
