### ISSUE TITLE
how to fix the order of the boxed through markdown? 

### ISSUE THREAD

**Issue by Hadi-Khatib** [syrianarchive/syrianarchive-http#27]
I'm not able to drag and drop through markdown. It's it's ordered alphabetically. 
![order-boxed](https://user-images.githubusercontent.com/8692315/33493581-c93de3b2-d6c0-11e7-9b56-2c7c62319627.png)

**Comment by nikonikoniko** [comment]
it should be ordered by date.  use the time for fine grained ordering.

ill make sure its actually ordered by date.

**Comment by nikonikoniko** [comment]
are these the right order now @Hadi-Khatib

**Comment by Hadi-Khatib** [comment]
yes they are good now
