### ISSUE TITLE
urgent:  fix broken links

### ISSUE THREAD

**Issue by nikonikoniko** [syrianarchive/syrianarchive-http#32]
There are a lot of links in the investigations that link to the old website structure.

even the most recent investigation:

https://syrianarchive.org/en/investigations/Three-Idlib-Medical-Facilities-Attacked.html

ctrl+f for "Syrian Archive has published an investigation" - that link goes to 404

I think it's worth doing a search in the directory of Pages, and look for any links to the old site url structure.

**Comment by tareefdev** [comment]
OK! I'll search in the Pages folder for this pattern "https://syrianarchive.org/p/page/" and modify all of old links.

**Comment by nikonikoniko** [comment]
i think the database ones are broken too, linking to specific incidents.

those will be a bit harder unfortunately :(

search there for `syrianarchive.org/database` and i think we have to search the database for the correct unit again.  

(if you need the old site up for help with this, i can put it up again at a different url, just let me know)

**Comment by nikonikoniko** [comment]
Also, i am happy to do this on my plane flight next week, if you all are too busy.

**Comment by tareefdev** [comment]
Thanks for you Niko, I can finish the task in these two days :)

**Comment by tareefdev** [comment]
I think that I need the old site to correct the links to our database :D

**Comment by nikonikoniko** [comment]
can you paste in an old link here that doesnt work?  I have an idea that might...

**Comment by tareefdev** [comment]
This one for example 
https://syrianarchive.org/database/?type_of_violation=16

and we have 68 links in total

**Comment by tareefdev** [comment]
BTW I just pushed a new [commit](https://github.com/syrianarchive/syrianarchive-http/commit/a56c08cc391ace1e08020fb631af3abe4fa547e4) which fixes the `syrianarchive.org/p/page/` links

**Comment by tareefdev** [comment]
I fixed all broken links :)

**Comment by nikonikoniko** [comment]
nice!
