### ISSUE TITLE
Add headers to the database

### ISSUE THREAD

**Issue by Hadi-Khatib** [syrianarchive/syrianarchive-http#4]
hash - incident date - description - location

![headers](https://user-images.githubusercontent.com/8692315/32776556-3a4ae3b6-c933-11e7-905d-a5bddf8a6693.png)

**Comment by nikonikoniko** [comment]
I don't think this is necessary.  I see everything as being quite self explanatory as to what it is.

the hash is not the hash, its just the reference ID.  I have moved it since.

**Comment by nikonikoniko** [comment]
If you really think it needs labels, assign back to me :)  

otherwise close
