### ISSUE TITLE
small size calender

### ISSUE THREAD

**Issue by Hadi-Khatib** [syrianarchive/syrianarchive-http#5]
resize calendar to make it bigger

![screenshot from 2017-11-13 17-19-51](https://user-images.githubusercontent.com/8692315/32776644-80abbb50-c933-11e7-805e-5f6310eb9b6b.png)

**Comment by tareefdev** [comment]
fixed [here](https://github.com/syrianarchive/syrianarchive-http/commit/0918b130b56bdcb868b69bfa161dd5568e927909)
