### ISSUE TITLE
"database of chemical weapons attacks" box 

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#5]
![chemicaldatabase_ar](https://user-images.githubusercontent.com/36305374/49285575-d466f380-f4a8-11e8-9f99-989a513b7a05.png)

https://syrianarchive.org/ar/collections/chemical-weapons/acknowledgements.html

the "database of chemical weapons attacks" box appears in English

**Comment by tareefdev** [comment]
Thanks, fixed
