### ISSUE TITLE
Filter doesn't show using chrome + MAC

### ISSUE THREAD

**Issue by Hadi-Khatib** [syrianarchive/syrianarchive-http#51]
![screen shot 2018-08-20 at 10 48 30 am](https://user-images.githubusercontent.com/8692315/44330434-491ca180-a467-11e8-9452-4263d95bd9a7.png)

**Comment by tareefdev** [comment]
The bug has been fixed [here](https://github.com/syrianarchive/syrianarchive-http/commit/1f15c294641b21e93fdeeae3c6c36d1f102b1b99), it'll deploy with other things today
