### ISSUE TITLE
Arabic translation for English strings in the database

### ISSUE THREAD

**Issue by Hadi-Khatib** [syrianarchive/syrianarchive-http#57]
![screen shot 2018-08-27 at 11 11 20 am](https://user-images.githubusercontent.com/8692315/44651676-4f23fc80-a9ea-11e8-81a4-22120253e70e.png)

**Comment by Hadi-Khatib** [comment]
Chemical weapons database - Key findings - Database. Also the search filters.

**Comment by tareefdev** [comment]
fixed [here](https://github.com/syrianarchive/syrianarchive-http/commit/bf9a1dc09306d6f677fa8e2c63d25050f981e37b), I'll deploy it tomorrow

**Comment by tareefdev** [comment]
[here](url)
