### ISSUE TITLE
english texts in the Arabic version of the database

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#6]
![chemicaldatabase-ar](https://user-images.githubusercontent.com/36305374/49285728-50f9d200-f4a9-11e8-9098-efc4a6918a23.png)

https://syrianarchive.org/ar/collections/chemical-weapons/database?term=cluster%20bombs%20was%20delivered%20by%20Russian%20aircraft%20flying%20over%20the%20western%20Aleppo

english texts in the Arabic version of the database

**Comment by tareefdev** [comment]
Thanks, fixed.
