### ISSUE TITLE
no footer or side boxes

### ISSUE THREAD

**Issue by Haneenk** [syrianarchive/syrianarchive-http#9]
![munitions-identified-no-footer](https://user-images.githubusercontent.com/36305374/49286037-3b38dc80-f4aa-11e8-816f-6db6b999e6dd.png)

https://syrianarchive.org/en/collections/russian-airstrikes/munitions_identified.html

no footer or side boxes in the "Munitions Identified" page, Arabic and English

**Comment by tareefdev** [comment]
Thanks, fixed.
